name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
  runs-on: ubuntu-lates
  steps:
    - name: pring greeting
      run: echo "Hello World!"
    - name: print goodbye
      run: echo "Done-Bye"
    
   
